"""empty message

Revision ID: 25063ff76ff1
Revises: cfa149174a51
Create Date: 2024-02-29 15:13:36.778472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25063ff76ff1'
down_revision = 'cfa149174a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commander_card_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cards', ['commander_card_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('commander_card_id')

    # ### end Alembic commands ###
