"""empty message

Revision ID: f25417b4d43e
Revises: cfa149174a51
Create Date: 2024-03-01 11:47:37.690076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25417b4d43e'
down_revision = 'cfa149174a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('deck_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'decks', ['deck_id'], ['id'])
        batch_op.drop_column('count')

    # ### end Alembic commands ###
