"""empty message

Revision ID: 60b7b5094ec4
Revises: ba310e61c84d
Create Date: 2024-03-28 16:01:05.159857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b7b5094ec4'
down_revision = 'ba310e61c84d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_image', sa.String(), nullable=False))
        batch_op.drop_column('previewImage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previewImage', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('preview_image')

    # ### end Alembic commands ###
